### ISSUE TITLE
Replace `franka_ros` submodule with binary package

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/panda-gazebo#162]
### Is your feature request related to a problem? Please describe.

The franka_ros package is currently included as a submodule due to pending features and fixes awaiting integration into the upstream repository. To maintain compatibility with our specific use case, we rely on a custom branch located [here](https://github.com/rickstaa/franka_ros/tree/develop-panda_gazebo). This branch contains several pull requests (PRs) essential for seamless operation but has yet to be merged into the upstream [develop] branch (https://github.com/frankaemika/franka_ros/tree/develop). Below, we'd like to list the required PRs and some optional enhancements.

#### Required Pull Requests

- [x] https://github.com/frankaemika/franka_ros/pull/226: Needed to allow users to set the robot joint positions.
- [ ] https://github.com/frankaemika/franka_ros/pull/211: Needed to allow users to use the `put_robot_in_world` launch file to start Gazebo using the [dart physics](https://dartsim.github.io/) engine. This engine is preferred when doing effort control since it is more stable than the [ODE](https://www.ode.org/) physics engine (see [franka_ros/issues/160](https://github.com/frankaemika/franka_ros/issues/160#issuecomment-989173918) for more information).
- [ ] https://github.com/frankaemika/franka_ros/pull/227: Required to address inaccuracies in collision checking within the upstream repository ([Issue #363](https://github.com/frankaemika/franka_ros/issues/363)).
- [ ] https://github.com/frankaemika/franka_ros/pull/228: Necessary to correct the external force calculation, which currently contains errors in the upstream ([Issue #364](https://github.com/frankaemika/franka_ros/issues/364)).
- [ ] https://github.com/frankaemika/franka_ros/pull/380: Needed due to a bug that was accidentally introduced in https://github.com/frankaemika/franka_ros/pull/226.

#### Nice to Have Enhancements

- https://github.com/frankaemika/franka_ros/pull/354: Resolves the CMake minimum version warning.
- https://github.com/frankaemika/franka_ros/pull/366: Eliminates a redundant robot namespace warning.
- https://github.com/frankaemika/franka_ros/pull/290: Enhances performance in both `franka_gazebo` and `franka_control`.
- https://github.com/frankaemika/franka_ros/pull/292: Ensures a fixed simulation rate.
- https://github.com/frankaemika/franka_ros/pull/370: Resolves a version incompatibility issue specific to Ubuntu 22.04.

### Some upstream problems that still exist and negatively affect this project

- https://github.com/frankaemika/franka_ros/issues/172: The simulated gripper is implemented suboptimal in [franka_ros](https://github.com/frankaemika/franka_ros).
  - Gripper PID gains need improvement for the `/franka_gripper/gripper_action/goal` Action to set the gripper width accurately when the gripper is vertical (see [this](https://github.com/frankaemika/franka_ros/pull/209#issuecomment-989159425) and [this](https://github.com/rickstaa/franka_ros/commit/8114ed28630851cd09eed7c92bac51a70ef1ee03) comment).
  - Additionally, there is a need to enhance the functionality of the `/franka_gripper/gripper_action/goal` action. The [gripperAction](https://frankaemika.github.io/docs/franka_ros.html#franka-gripper) currently has a limitation—it can only grasp objects when the gripper width is explicitly specified. On the other hand, the [grasp](https://frankaemika.github.io/docs/franka_ros.html#franka-gripper) action can grasp things but cannot set a desired gripper width. In reinforcement learning, it would be advantageous for the robot to autonomously learn and set the gripper width while grasping objects, even without prior knowledge of the object size.
- https://github.com/frankaemika/franka_ros/issues/233: The gravity compensation for the simulated panda in [franka_ros](https://github.com/frankaemika/franka_ros) is dysfunctional, leading to unintended drift when utilizing effort controllers with an attached hand.

### Proposed Solution

Once all the mentioned PRs have been successfully merged into the upstream repository, we can use the official binary package for `franka_ros`.
